### ISSUE TITLE
Unable to install repo - can't checkout private graphIK-internal repo

### ISSUE THREAD

**Issue by jangerritha** [utiasSTARS/generative-graphIK#1]
Hello everyone,

I tried to checkout your repo and install it by using `pip install -e .`.

However, one needs access to your `github.com/utiasSTARS/graphik-internal` repo, which is private.

Do you have any instructions/help to install it?

I am working in robotics research and wanted to investigate your repo.

**Comment by jangerritha** [comment]
Error Message:

```
Obtaining file:///export/home/habekost/repositories/generative-graphIK
  Preparing metadata (setup.py) ... done
Collecting liegroups@ git+ssh://git@github.com/utiasSTARS/liegroups@generative_ik#egg=liegroups (from generative-graphik==0.1)
  Cloning ssh://****@github.com/utiasSTARS/liegroups (to revision generative_ik) to /tmp/pip-install-8kmjjp0d/liegroups_906043dacd8c4bada9e1d366e06ece97
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/utiasSTARS/liegroups' /tmp/pip-install-8kmjjp0d/liegroups_906043dacd8c4bada9e1d366e06ece97
  Running command git checkout -b generative_ik --track origin/generative_ik
  Switched to a new branch 'generative_ik'
  Branch 'generative_ik' set up to track remote branch 'generative_ik' from 'origin'.
  Resolved ssh://****@github.com/utiasSTARS/liegroups to commit 020c9a3a1bde511a3ad5febeee9dd201146a5b02
  Preparing metadata (setup.py) ... done
Collecting graphIK@ git+ssh://git@github.com/utiasSTARS/graphik-internal@main#egg=graphIK (from generative-graphik==0.1)
  Cloning ssh://****@github.com/utiasSTARS/graphik-internal (to revision main) to /tmp/pip-install-8kmjjp0d/graphik_82950b6719044491b4438d8634481ea3
  Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/utiasSTARS/graphik-internal' /tmp/pip-install-8kmjjp0d/graphik_82950b6719044491b4438d8634481ea3
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet 'ssh://****@github.com/utiasSTARS/graphik-internal' /tmp/pip-install-8kmjjp0d/graphik_82950b6719044491b4438d8634481ea3 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet 'ssh://****@github.com/utiasSTARS/graphik-internal' /tmp/pip-install-8kmjjp0d/graphik_82950b6719044491b4438d8634481ea3 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by Olimoyo** [comment]
Hi,

The `setup.py` file wasn't updated but it should be now (see 2c36875ccd12a7c690f75f27e303ec965aa7fbc5).

The code should work with the public branch of GraphIK.

**Comment by jangerritha** [comment]
Thank you for the quick response.

There is still a copy-and-paste bug but with your information I was able to fix it:

Had to change [this line](https://github.com/utiasSTARS/generative-graphIK/blob/2c36875ccd12a7c690f75f27e303ec965aa7fbc5/setup.py#L23) to:

`"graphIK @ git+ssh://git@github.com/utiasSTARS/graphIK"`


I'm excited to run your application.

We just published our novel semi-humanoid [NICOL robot](https://arxiv.org/abs/2305.08528) which we have developed in the [Knowledge Technology Group](https://www.inf.uni-hamburg.de/en/inst/ab/wtm.html) at the University of Hamburg.

In addition, we developed a neuro-inspired inverse kinematics method, [CycleIK](https://arxiv.org/abs/2307.11554).


CycleIK achieves similar results as IKFlow and as I saw that you compare your method to IKFlow, I thought it might be of interest to you. If you are interested in exchanging thoughts or ideas don't hesitate to contact me.

Your method is the third neural architecture I know of that is capable of achieving <1cm error, congratulations.

**Comment by Olimoyo** [comment]
Thank you for the catch and fix - pushed an update.

I'm happy that you're going to try GGIK, please feel free to message or open any issues if you have some questions. Also happy to exchange thoughts and ideas regarding learned IK!

CycleIK looks interesting, I will give it a read :).
